---
functional:
  - Успешная регистрация пользователя (+ негативные сценарии);
  - Успешная авторизация пользователя (+ негативные сценарии);
  - Успешный выбор партнера для игры (любой человек, бот, друг + негативные сценарии);
  - Успешная видимость кода соперника в игре и вывода тестов;
  - Успешная смена языка программирования во время решения участником;
  - Успешный выбор уровня сложности игры;
  - Успешный выбор определенной игры;
  - Успешное начало игры без опредленного выбора - любой сценарий игры;
  - Успешное сохранение игы в виде записи;
  - Успешный вывод на просмотр записанной игры;
  - Возможность следить за ходом игры другим пользователям;
  - Возможность общения зарегистрированных пользователей в чате;
  - Успешное начисление очков за игру;
  - Начисленные очки с каждой игрой увеличиваются (складываются);
  - Отслеживание начисленных очков на протяжении длительного времени и вывод в профиле пользователя (обновление и сохранение в БД);
non-functional:
  - Выдор языка вывода задачи (русский и англ);
  - Корректный переход по ссылкам и кнопкам;
  - Понятный интерфейс пользователя (видны и понятны все необходимые переходы, названия);
  - Адаптивность сайта под разные устройства;
  - Успешная совместимость с последними версиями браузеров (кроссбраузерность);
  - Скорость отклика системы не должна превышать 1 сек в режиме 1 игры без наблюдающих;
  - Возможность обработки трафика 1000 пользователей одновременно;
  - Возможность выдерживать пиковые нагрузки более 1000 пользователей одновременно;
  - Безопасность данных пользователей в БД;
implicit:
  - Возможность участия в игре более 2-х игроков;
  - Локализация под разные страны (международный турнир?);
