---
functional:
  - Успешная регистрация пользователя;
  - Неуспешная регистрация пользователя при Nickname < 3 символов ;
  - Неуспешная регистрация пользователя при Nickname > 16 символов ;
  - Неуспешная регистрация пользователя при валидном Nickname в кириллице;
  - Неуспешная регистрация пользователя при невалидном E-mail;
  - Неуспешная регистрация пользователя при пароле < 3 символов; 
  - Неуспешная регистрация пользователя при пароле > 16 символов;
  - Неуспешная регистрация пользователя при несовпадении подтверждения пароля; 
  - Неуспешная регистрация пользователя с занятым Nickname;
  - Неуспешная регистрация пользователя с занятым E-mail;
  - Успешная авторизация пользователя;
  - Успешная авторизация пользователя через Github;
  - Успешная авторизация пользователя с Discord;
  - Неуспешная авторизация пользователя при невалидном E-mail;
  - Неуспешная авторизацяи пользователя при неверном Password;
  - Неуспешная авторизация незарегистрированного пользователя
  - Успешная отправка письма на указанную почту по ссылке Забыли пароль?;
  - Успешное восстановления пароля;
  - Успешный проведение игры для незарегистрированного и неавторизованного пользователя;
  - Успешный выбор языка программирования для решения задачи;
  - Успешный окончание игры через сдачу;
  - Успешное обновление редактора задачи до первоначального состояния;
  - Успешный запуск решения на выполнение;
  - Успешная отправк сообщений в чат;
  - Успешный просмотр истории игры;
  - Успешный переход по кнопке Rematch / Матч-реванш;
  - Успешный выбор соперника (бот);
  - Успешная отправка сообщения при выборе соперника;
  - Успешная отправка приглашения на битву;
  - Успешный просмотра игры завершенного турнира;
  - Успешный просмотр завершенных игр;
  - Успешное создание новой игры по заданным параметрам;
non-functional:
  - Успешное открытие пошаговой инструкции пользователя;
  - Успешное переключение между шагами в инструкции пользователя; 
  - Успешный переход по кнопкам в соответствии с их названием;
  - Успешный выбор темы экрана; 
  - Успешный вывод информации по проведённым играм пользователя;
  - Успешная смена типа чата; 
  - Успешная настройка скорости просмотра игры;  
  - Упешное копирование ссылки игры;
  - Успешный просмотр истории игры по скопированной ссылке; 
  - Успешный просмотр истории игры по скопированной ссылке отправленной в теле письма;
  - Успешная отправка отзыва Send Feedback / Прислать отзыв;
  - Успешное формирование таблицы лидеров за определенный период;
  - Успешный просмотр TOP list лидеров за определенный период;
  - Успешная сортировка пользователей по разным данным;
  - Успешный поиск пользователя в таблице рейтинга;
  - Корректная адаптация сайта под разные устройства;
  - Корректное отображение сайта в разных масштабах;
  - Успешное переключение языка вывода текста задачи;
  - Успешная совместимость с последними версиями браузеров (кроссбраузерность);
  - Скорость отклика системы;
  - Возможность обработки большого трафика пользователей одновременно;
  - Возможность выдерживать пиковые нагрузки пользователей одновременно;
  - Безопасность данных пользователей в БД;
implicit:
  - Возможность участия в игре более 2-х игроков;
  - Локализация под разные страны (международный турнир?);
