---
functional:
  - Проверка регистрации пользователя;
  - Проверка регистрации пользователя при Nickname < 3 символов ;
  - Проверка регистрации пользователя при Nickname > 16 символов ;
  - Проверка регистрации пользователя при валидном Nickname в кириллице;
  - Проверка регистрации пользователя при невалидном E-mail;
  - Проверка регистрации пользователя при пароле < 3 символов; 
  - Проверка регистрации пользователя при пароле > 16 символов;
  - При вводе Password более 16 символов появится требование Should be from 3 to 16 characters;
  - Проверка регистрации пользователя при несовпадении подтверждения пароля; 
  - Проверка регистрации пользователя с занятым Nickname;
  - Проверка регистрации пользователя с занятым E-mail;
  - Проверка авторизации пользователя;
  - Проверка авторизации пользователя через Github;
  - Проверка авторизации пользователя с Discord;
  - Проверка авторизации пользователя при невалидном E-mail;
  - Проверка авторизации пользователя при неверном Password;
  - Проверка авторизации незарегистрированного пользователя
  - Проверка отправки письма на указанную почту по ссылке Забыли пароль?;
  - Проверка восстановления пароля;
  - Возможность проведения игры для незарегистрированного и неавторизованного пользователя;
  - Проверка выбора языка программирования для решения задачи;
  - Проверка окончание игры через сдачу;
  - Проверка обновления редактора задачи до первоначального состояния;
  - Проверка запуска решения на выполнение;
  - Возможность отправки сообщений в чат;
  - Проверка просмотра истории игры;
  - Проверка перехода по кнопке Rematch / Матч-реванш;
  - Проверка выбора соперника (бот);
  - Возможность отправки сообщения при выборе соперника;
  - Возможность отправки приглашения на битву;
  - Проверка просмотра игры завершенного турнира;
  - Проверка просмотра завершенных игр;
  - Проверка создания новой игры по заданным параметрам;
non-functional:
  - Проверка открытия пошаговой инструкции пользователя;
  - Проверка переключения между шагами в инструкции пользователя; 
  - Переход по кнопкам осуществляется в соответствии с их названием;
  - Проверка выбора темы экрана; 
  - Вывод информации по проведённым играм пользователя;
  - Проверка смены типа чата; 
  - Возможность настройки скорости просмотра игры;  
  - Проверка копирования ссылки игры;
  - Проверка просмотра истории игры по скопированной ссылке; 
  - Проверка просмотра истории игры по скопированной ссылке отправленной в теле письма;
  - Возможность отправки отзыва Send Feedback / Прислать отзыв;
  - Проверка формирования таблицы лидеров за определенный период;
  - Возможность просмотра TOP list лидеров за определенный период;
  - Проверка сортировки пользователей по разным данным;
  - Возможность поиска пользователя в таблице рейтинга;
  - Проверка корректности адаптация сайта под разные устройства;
  - Корректное отображение сайта в разных масштабах;
  - Проверка переключение языка вывода текста задачи;
  - Успешная совместимость с последними версиями браузеров (кроссбраузерность);
  - Скорость отклика системы;
  - Возможность обработки большого трафика пользователей одновременно;
  - Возможность выдерживать пиковые нагрузки пользователей одновременно;
  - Безопасность данных пользователей в БД;
implicit:
  - Возможность участия в игре более 2-х игроков;
  - Локализация под разные страны (международный турнир?);
