---
functional:
  - Успешная регистрация пользователя;
  - Пользователь не зарегиструется при невалидных данных;
  - Пользователь не зарегиструется используя занятые входные данные; 
  - Успешная авторизация пользователя;
  - Успешная авторизация пользователя через сервисы;
  - Зарегистрированный пользователь не авторизуется при неверных входных данных;
  - Незарегистрированный пользователь не может авторизовться;
  - Возможность восстановливать пароль;
  - Успешный выбор соперника для игры;
  - Возможность проведения игры для незарегистрированным и неавторизованноым пользователем;
  - Возможность выбора языка программирования для решения задачи;
  - Возможность общения соперников в чате;
  - Успешная смена языка программирования во время решения участником; 
  - Возможность создать новую игру по заданным параметрам;
  - Возможность переключения языка вывода текста задачи;
  - Успешный выбор уровня сложности игры;
  - Успешный выбор определенной игры;
  - Успешный вывод на просмотр записанной игры;
  - Возможность следить за ходом игры другим пользователям;
  - Возможность общения зарегистрированных пользователей в чате;
  - Возможность просмотра информации по проведённым играм пользователя;
  - Возможность отправить отзыв;
  - Возможность отслеживать рейтинг играков;
  - Возможность найти нужного игрока;
non-functional:
  - Возможность изменить тему экрана; 
  - Корректный переход по ссылкам и кнопкам;
  - Корректная адаптация сайта под разные устройства;
  - Корректное отображение сайта в разных масштабах;
  - Успешная совместимость с последними версиями браузеров (кроссбраузерность);
  - Скорость отклика системы не должна превышать 1 сек в режиме 1 игры без наблюдающих;
  - Возможность обработки трафика 1000 пользователей одновременно;
  - Возможность выдерживать пиковые нагрузки более 1000 пользователей одновременно;
  - Безопасность данных пользователей в БД;
implicit:
  - Возможность участия в игре более 2-х игроков;
  - Локализация под разные страны (международный турнир?);
