---
functional:
  - Успешная регистрация пользователя с валидными данными;
  - Пользователь не зарегиструется при невалидных данных;
  - Пользователь не зарегиструется используя занятые входные данные;
  - Успешная авторизация зарегистрированного пользователя;
  - Успешная авторизация пользователя через сервисы;
  - Зарегистрированный пользователь не авторизуется при неверных входных данных;
  - Незарегистрированный пользователь не может авторизовться;
  - Возможность восстановливать пароль;
  - Возможность проведения игры для незарегистрированным и неавторизованноым пользователем;
  - Возможность выбора языка программирования для решения задачи;
  - Возможность общения соперников в чате;
  - Возможность просмотра истории игры;
  - Возможность выбора соперника (бот, человек);
  - Возможность создать новую игру по заданным параметрам;
  - Возможность переключения языка вывода текста задачи; 
  - Возможность просмотра информации по проведённым играм пользователя;
  - Возможность отправить отзыв;
  - Возможность отслеживать рейтинг играков;
  - Возможность найти нужного игрока;
non-functional:
  - Возможность изменить тему экрана; 
  - Корректная адаптация сайта под разные устройства;
  - Корректное отображение сайта в разных масштабах;
  - Успешная совместимость с последними версиями браузеров (кроссбраузерность);
  - Скорость отклика системы;
  - Возможность обработки большого трафика пользователей одновременно;
  - Возможность выдерживать пиковые нагрузки пользователей одновременно;
  - Безопасность данных пользователей в БД;
implicit:
  - Возможность участия в игре более 2-х игроков;
  - Локализация под разные страны (международный турнир?);
